version: "3"

services:
  database:
    image: mongo:3.6.0
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_DATABASE: univision
    volumes:
      - ./db.init.js:/docker-entrypoint-initdb.d/a.js:ro
  web:
    build: ../
    ports:
      - ${PORT}:2525
    depends_on:
      - database
    env_file:
      - .env
    command: >
      /bin/bash -c "
        sleep 5;
        npm run server:start;
      "
