export default {
  SET_FEEDS: "SET_FEEDS",
  ADD_FEED: "ADD_FEED",
  IS_LOADING: "IS_LOADING",
  SET_ERRORS: "SET_ERRORS",
  UPDATE_FEED_LINKS: "UPDATE_FEED_LINKS",
  IS_ADDING_FEED: "IS_ADDING_FEED"
};
